[tools]
fd = "latest"
fzf = "latest"
go = "latest"
golangci-lint = "latest"
lua-language-server = "latest"
neovim = "latest"
ninja = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
"vfox:version-fox/vfox-cmake" = "3.27"
yazi = "latest"
zig = "latest"
zoxide = "latest"

[settings]
asdf = false
vfox = true
idiomatic_version_file_enable_tools = ["ruby"]
